### ISSUE TITLE
Can't close connection

### ISSUE THREAD

**Issue by webnard** [evs-chris/node-postgres-gen#1]
Is there a way to close a connection manually after performing a query? Looking through the source code, I don't see any way to access the underlying client or any public methods to close the connection. I might be looking in the wrong place, though.

**Comment by webnard** [comment]
See #2

**Comment by evs-chris** [comment]
You can turn off pooling and the connection will automatically be closed at a transactional boundary. So for a single statement, it would open a connection, run the query, and close the connection. For transactions, once the transaction is closed, the connection will also be closed.

``` js
var db = require('postgres-gen')({ string: 'postgresql://...', pool: false });

db.transaction(function*(t) { // connection opens
  var rows = (yield t.query('select something from somewhere')).rows;
  t.nonQuery('update foo set bar = ?', 'baz');
});
// connection is closed
```

I wouldn't think you'd want to close a connection while using a pool.

**Comment by webnard** [comment]
Thanks, @evs-chris! I'm new to postgres; sorry for the silly question. This fixes my issue. I was nuking and restoring a database during automated testing, but I couldn't do that without closing said connections. Now I just can set the pool to false on my automated tests.
